export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const REPLY_COMMENT = 'REPLY_COMMENT';
